### ISSUE TITLE
Sunrise time difference

### ISSUE THREAD

**Issue by deandreamatias** [renancaraujo/daylight#2]
version: 1.0.0

I compare a time in sunrise-sunset API with your package. 
In sunset in the same time in my location (39.4699014, -0.3759513), day 2020-03-03 and Zennit default (official). 
But in sunrise, have a litle difference of 56 seconds . This is a screenshots and values
API - Sunrise **07:29:48**: 
![image](https://user-images.githubusercontent.com/21011641/75787716-65d9ab00-5d67-11ea-8da3-c883a4d09c6f.png)
Package - Sunrise **07:30:44**:
![image](https://user-images.githubusercontent.com/21011641/75787781-83a71000-5d67-11ea-9a96-7446d7f13107.png)

OBS: This is a minor issue and I'll use this package because is awesome :)

**Comment by renancaraujo** [comment]
What zenith are you using?

**Comment by deandreamatias** [comment]
I update the issue @renancaraujo

**Comment by renancaraujo** [comment]
WE probably have an issue due to math approximations (and the algorithm itself). I don't think we have to expect absolute precision here.

**Comment by deandreamatias** [comment]
I will close this issue for now. If hace update, we can open again.
Thanks for answer
