### ISSUE TITLE
Civil sunrise and sunset off by 30 mins

### ISSUE THREAD

**Issue by pranaykothari** [renancaraujo/daylight#4]
Hello,

Thanks for a very useful library. 

I have found that the calculated date time is off by 30 mins and hence we need to add this to get the correct value after calculation. Here's what I ended up writing:
```dart
  SunTime _fromLibrary2({DateTime dateTime}) {
    //uses this package: daylight
    berlin();

    //const lc = const DaylightLocation(52.518611, 13.408056);
    final lc = DaylightLocation(latitude, longitude);

    // Create lc calculator
    final lcCalculator = DaylightCalculator(lc);

    //this is the closest, but still early by 30 mins
    final daylightResult =
        lcCalculator.calculateForDay(dateTime ?? DateTime.now());

    //correct the difference of 30 mins
    return new SunTime(
        daylightResult.sunrise.round().add(Duration(minutes: 30)),
        daylightResult.sunset.round().add(Duration(minutes: 30)));
  }

/// Result of SunriseSunset calculation
class SunTime {
  /// Construnctor method
  SunTime(this.sunrise, this.sunset);

  /// Time of the sunrise
  DateTime sunrise;

  /// Time of the sunset
  DateTime sunset;

  String localSunriseDisplay() =>
      '${sunrise.toLocal().hour}:${sunrise.toLocal().minute}';
  String localSunsetDisplay() =>
      '${sunset.toLocal().hour}:${sunset.toLocal().minute}';

  @override
  String toString() =>
      'Sunrise: $localSunriseDisplay, Sunset: $localSunsetDisplay';
}

extension Round on DateTime {
  DateTime round({roundAtSeconds = 30}) {
    var factor =
        this.second <= roundAtSeconds ? (-1 * this.second) : (60 - this.second);
    return this.add(Duration(seconds: factor));
  }
}
```
Can you please confirm if this is so. And if the issue is correct, kindly update the package.

**Comment by ricardopaulob** [comment]
I found a similar issue. Here in Brazil the calculation is 23 minutes wrong (less for sunrise and more for sunset).

So, to fix, I need to use
    daylightResult.sunrise.round().add(Duration(minutes: 23)),
    daylightResult.sunset.round().add(Duration(minutes: -23)));

**Comment by renancaraujo** [comment]
We may have some imprecision on the doubles that are causing these imprecisions. Also, we have some factors that may change the exact time of the sun events, like altitude.

**Comment by renancaraujo** [comment]
I am gonna do some more tests on it, but be aware that this line can not be as precise as an API-based one, that in general take all factors into consideration, not only the mathematical ones.

**Comment by renancaraujo** [comment]
Oh god, after some serious time debugging I think I know the real problem here.

If you wanna calculate the time for civil sunset and sunrise, you need to specify the zenith on calculateForDay, where it defaults to `official`.

```dart
final daylightResult =
        lcCalculator.calculateForDay(dateTime ?? DateTime.now(), Zenith.civil);
        
```

**Comment by renancaraujo** [comment]
I guess we can close this?

**Comment by ricardopaulob** [comment]
Yes, sure. You can close this. For me it is perfect as it is.
