### ISSUE TITLE
please migrate the package to intl 0.17.0

### ISSUE THREAD

**Issue by cyclone-pk** [renancaraujo/daylight#8]
I am using day package in my app and now after upgrading to latest flutter sdk i am unable to use the day light package. 
error message I get is the following.

Because no versions of daylight match >0.2.0 <0.3.0 and daylight 0.2.0 depends on intl ^0.16.1, daylight ^0.2.0 requires intl ^0.16.1.
And because every version of flutter_localizations from sdk depends on intl 0.17.0, daylight ^0.2.0 is incompatible with flutter_localizations from sdk.
So, because tiremoni depends on both flutter_localizations any from sdk and daylight ^0.2.0, version solving failed.
pub get failed (1; So, because tiremoni depends on both flutter_localizations any from sdk and daylight ^0.2.0, version solving failed.)

**Comment by renancaraujo** [comment]
Just opened a PR for that: https://github.com/renancaraujo/daylight/pull/7

**Comment by renancaraujo** [comment]
Fixed on 2.0.0
